In [42]:
import json
import pandas as pd

with open("data/bands_genres_cleaned.json", encoding="utf-8") as f:
    bands = json.load(f)

bands = pd.DataFrame(list(bands.items()), columns=["artiste", "genre"])
print(bands["genre"].apply(type).value_counts())
print(bands.head())

genre
<class 'list'>        72
<class 'NoneType'>    28
Name: count, dtype: int64
        artiste                                    genre
0  Judas Priest                            [Heavy Metal]
1  Alice Cooper                                     None
2          Rage              [Heavy, Speed, Power Metal]
3  Unholy Grave      [Grindcore, Death Metal, Noisecore]
4  Napalm Death  [Hardcore Punk, Grindcore, Death Metal]

In [26]:
with open("data/dataset.json", encoding="utf-8") as f:
    chansons = json.load(f)

rows=[]
for _,artist in chansons["dataset"].items() :
    for _, album in artist.get("albums", {}).items():
        for song in album.get("songs", []):
            rows.append({
                "artiste" : artist.get("name"),
                "album" : album.get("name"),
                "annee" : album.get("release_year"),
                "titre" : song.get("title"),
                "paroles" : song.get("lyrics")
            })

songs = pd.DataFrame(rows)
print(songs.shape)
print(songs.head())

(257716, 5)
  artiste                 album annee      titre  \
0     '68  In Humor And Sadness  2014  Track 1 R
1     '68  In Humor And Sadness  2014  Track 2 E
2     '68  In Humor And Sadness  2014  Track 3 G
3     '68  In Humor And Sadness  2014  Track 4 R
4     '68  In Humor And Sadness  2014  Track 5 E

                                             paroles
0  Take your heart into the next room.\nMake a sc...
1  It doesn't matter what you say,\nThey could al...
2  Hey kid, don't listen to them.\nWe got a long,...
3  Stained glass.\nI wish that I could say that i...
4  I've been taken to the edge of it all.\nI've b...

In [27]:
songs[songs["artiste"] == "'68"]

,artiste,album,annee,titre,paroles
0,'68,In Humor And Sadness,2014,Track 1 R,Take your heart into the next room.\nMake a sc...
1,'68,In Humor And Sadness,2014,Track 2 E,"It doesn't matter what you say,\nThey could al..."
2,'68,In Humor And Sadness,2014,Track 3 G,"Hey kid, don't listen to them.\nWe got a long,..."
3,'68,In Humor And Sadness,2014,Track 4 R,Stained glass.\nI wish that I could say that i...
4,'68,In Humor And Sadness,2014,Track 5 E,I've been taken to the edge of it all.\nI've b...
5,'68,In Humor And Sadness,2014,Track 6 T,Over thought.\nUndersold.\nI have sung every s...
6,'68,In Humor And Sadness,2014,Track 7 N,"The future has seen better days.\nAlways, clos..."
7,'68,In Humor And Sadness,2014,Track 8 O,"Hey, I still got a lot to say.\nMaybe I'm wron..."
8,'68,In Humor And Sadness,2014,Track 9 T,I can understand your hesitation but\nYou can'...
9,'68,In Humor And Sadness,2014,Track 10 .,Barricade all of your fears and we'll speak to...

In [28]:
songs.groupby("artiste")["album"].nunique()

artiste
'68                1
(Sic)Monic         2
+\-                1
...Aaaarrghh...    3
...And Oceans      5
                  ..
Ásmegin            2
Íon                2
Öoooooooooo        1
Øscillatör         1
Žalvarinis         1
Name: album, Length: 8637, dtype: int64

In [29]:
songs.query("artiste == '(Sic)Monic' and album == 'Look To The Skies'")

,artiste,album,annee,titre,paroles
10,(Sic)Monic,Look To The Skies,2006,Fist To Throat,Every time I look I feel\nevery time sentiment...
11,(Sic)Monic,Look To The Skies,2006,Seven Inches Deep,I heard a man once say before he faded away I ...
12,(Sic)Monic,Look To The Skies,2006,My Own Reflection,Ill be the victim bleeding in the gutter you b...
13,(Sic)Monic,Look To The Skies,2006,Blood Shot,This is the blood of the weak blanketed in sac...
14,(Sic)Monic,Look To The Skies,2006,Silent Screams,[Pre-verse:]\n\nInfinite is how I dream silent...
15,(Sic)Monic,Look To The Skies,2006,Hypnotic,So beautiful your own sense of hypnotic face d...
16,(Sic)Monic,Look To The Skies,2006,Shadow Bound,Never meant to compromise born to indefinitely...
17,(Sic)Monic,Look To The Skies,2006,Forever And A Day,[Chorus:]\n\nWhence forth she came we breathed...
18,(Sic)Monic,Look To The Skies,2006,Dementia,[Chorus:]\n\nCatatonic so symphonic eyes demon...
19,(Sic)Monic,Look To The Skies,2006,Desensitized,Suffocate the voices penetrate the noises thro...
20,(Sic)Monic,Look To The Skies,2006,Cracks In The Pavement,This is the harmony derived from symphonies th...
21,(Sic)Monic,Look To The Skies,2006,Black Hole Rebirth,Softly it fades bleeding for days come inside ...
22,(Sic)Monic,Look To The Skies,2006,Devil Went Down To Georgia,

In [51]:
bands_long = bands.explode("genre").reset_index(drop=True) #une ligne par genre
# on retire le mot Metal des genres
bands_long["genre"] = (
    bands_long["genre"]
    .str.replace(r"\bmetal\b", "", case=False, regex=True)
    .str.strip()
)
heavy = bands_long.query("genre == 'Heavy'")["artiste"]
heavy

0        Judas Priest
2                Rage
12          Motorhead
22              Saxon
34       Grave Digger
36           W.A.S.P.
41     Axel Rudi Pell
46              Anvil
51           Loudness
56         Mägo De Oz
61           Savatage
65      Black Sabbath
67      Virgin Steele
69      Virgin Steele
85           Megadeth
89       Running Wild
92             Accept
106      King Diamond
115         Metallica
129     Ozzy Osbourne
131           Stryper
144       Iron Maiden
167           Manowar
169             Lordi
182               Dio
183            Dokken
Name: artiste, dtype: object

In [53]:
songs.query("artiste in @heavy").head()

,artiste,album,annee,titre,paroles
4203,Accept,Accept,1979,Lady Lou,Running through empty streets\nTry to find my ...
4204,Accept,Accept,1979,Tired Of Me,Rain wets your body - rain wets the streets\nB...
4205,Accept,Accept,1979,Seawinds,In a cold and dark December\nAs I walked into ...
4206,Accept,Accept,1979,Take Him In My Heart,Once upon a time\nThere was a girl so young an...
4207,Accept,Accept,1979,Sounds Of War,Sounds of chains we hear from far behind\nMech...